Main page
scrat98/aviasales-demo-frontend pull request #3
Opened 2018-02-17 07:03 UTC by scrat98

Finished working. Please tell me about my mistakes

2018-02-17 16:40 UTC, evgenyrodionov commented
https://codesandbox.io/s/github/scrat98/aviasales-demo-frontend/tree/main_page

2018-02-17 16:42 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/36343218-647c48be-141a-11e8-9f2a-6f8afb33b50f.png)
![image](https://user-images.githubusercontent.com/775692/36343219-6919ca0e-141a-11e8-88b4-129d3a3c9e9f.png)

![image](https://user-images.githubusercontent.com/775692/36343221-7578aca2-141a-11e8-898b-1b5b5571b79f.png)

![image](https://user-images.githubusercontent.com/775692/36343227-82bc1ff2-141a-11e8-9fe3-56c7d624c333.png)
![image](https://user-images.githubusercontent.com/775692/36343230-89685ab4-141a-11e8-996a-eda19aae80ca.png)
![image](https://user-images.githubusercontent.com/775692/36343231-8fe8d4e0-141a-11e8-8df5-f9b5fbe56818.png)
![image](https://user-images.githubusercontent.com/775692/36343239-9614772a-141a-11e8-8db7-21c13a0d77b1.png)
![image](https://user-images.githubusercontent.com/775692/36343240-9bab6324-141a-11e8-9a6b-980dc1f0ad38.png)
![image](https://user-images.githubusercontent.com/775692/36343243-a04fc4d8-141a-11e8-91ce-8769ae7b80af.png)

2018-02-17 16:43 UTC, imevro requested changes
по коду вроде сносно, но от количества врапперов я охуеваю

2018-02-17 17:43 UTC, scrat98 commented
если посмотреть на футер и на карточки с городами в песочнице, то их педорасит, он почему то стили col- не просасывает. Вот я тунель открыл, можешь сравнить, ничего не изменял пока что. http://af415de3.ngrok.io/
вот ишью на гитхабе https://github.com/CompuIves/codesandbox-client/issues/171
![](https://i.imgur.com/N5QdNrl.png)

2018-02-17 20:58 UTC, scrat98 commented
Недочеты исправил. Тунель больше не открыт, но можно локально собрать - это я про косяк с песочницей

2018-02-19 16:47 UTC, imevro approved these changes

2018-02-19 16:47 UTC, merged